version: 0.2

phases:
    install:
      commands:
        - echo Installing Bundler...
        - gem install bundler
        - bundle install --deployment
    pre_build:
      commands:
        - DATABASE_URL=$DATABASE_URL RAILS_ENV=$RAILS_ENV bundle exec rake db:migrate