# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
universities = [
    {:rank => 1, :university_name => 'Massachusetts Institute of Technology', :university_type => 'Private', :acceptance_rate => 18,
     :tuition => '$49,600', :location => 'Located in Cambridge, Massachusetts, MIT is located on the north shore of the Charles River Basin. The campus is within 3 miles of two major interstate highways, and is less than 6 miles from Logan international airport. The Kendall (or MIT) Station is at a 5 minute walk from the campus. MIT is roughly a 20 minute walk from downtown Boston, and a 30–40 minute walk from Harvard University, which is located just up the river from the MIT campus.',
     :weather => 'If there’s any negative about MIT, then this is it. The climate here is of the continental type. Massachusetts receives about 40 inches of rain annually, fairly evenly distributed throughout the year, slightly wetter during the winter.Summers are warm with average high temperatures in July about 26.7 °C and overnight lows about 15.5 °C. Winters are pretty cold though, with temperatures often going sub-zero.',
     :university_link => 'http://www.mit.edu/', :university_desc => "Although it’ll no doubt be fascinating and highly inspiring to read about MIT, it could also give you a serious inferiority complex. Because Massachusetts Institute of Technology is perhaps the best overall college in the world, and it makes sure its students are no less. To get into MIT, you need to be excellent in everything, and even that probably won’t be enough. MIT is absolutely top-notch in everything, from infrastructure to faculty to extracurriculars to placements to alumni. An interesting bit of trivia: the aggregated revenues of companies founded by MIT alumni would rank as the eleventh largest economy in the world. Now, that's MIT. We associate only one word with MIT - WOW."},

    {:rank => 2, :university_name => 'Stanford University', :university_type => 'Private', :acceptance_rate => 17,
     :tuition => '$16,900', :location => 'Located 35 miles south of San Francisco and 20 miles north of San Jose, Stanford University is in the heart of Northern California’s dynamic Silicon Valley.',
     :weather => 'Most students are of the common opinion that the weather at Stanford is pretty good. Apart from the winter months, when it’s slightly cold and wet, the rest of the year is sunny and pleasant. Stanford University area doesn’t receive snowfall and fortunately doesn’t experience extremes of temperature. It’s pretty normal to see people roaming around in shorts and tshirts.',
     :university_link => 'http://www.stanford.edu/', :university_desc => "The very famous Stanford University is a private research university with a high output, located in Stanford, California. Simply, if anyone gets into Stanford, she/he takes it blindly, as the acceptance rate is a mere 4.8% and financial aids are among the most generous ones. To get an idea of exactly how competitive Stanford is, you don’t have to look further than the long list of prominent companies founded by Stanford alumni- Google, Hewlett-Packard, LinkedIn, Yahoo, and Sun Microsystems. And that’s not even one tenth of the list. Also, it ranks #3 according to U.S. News' 'Best Global Universities Ranking' list."},

    {:rank => 3, :university_name => 'University of California – Berkeley', :university_type => 'Public', :acceptance_rate => 14,
     :tuition => '$28,000', :location => 'University of California – Berkeley is located in the Bay Area of California, a very in-demand and rather expensive area. The university is roughly 5 miles from Oakland, and 12 miles from San Francisco. Anyone who knows will tell you that UC Berkeley has a fantastic location, with Tilden Park and Berkeley Marina pretty close by.',
     :weather => 'Berkeley has a Mediterranean climate, though the temperatures in general are rather lower than what you come to expect in, say, Spain. Summers are cool and dry, while winters are cold and wet. Average temperatures in September (the ‘hottest’ month) are a high of 22.1°C and a low of 13.3°C, while average temperatures in January (the coldest month) are a high of 13.6°C and a low of 6.4°C. Berkeley also experiences rainfall once in a while, mainly during winters, and not much. Snowfall is a rare commodity, and normally takes place only on the peaks of hills.',
     :university_link => 'https://www.berkeley.edu/', :university_desc => "UC Berkeley is the flagship institute of the University of California. Statistically, Berkeley (as it’s called) is the most consistently well ranked university in the world. It has the highest number of distinguished graduate programs ranked in the top 10 in their fields by the United States National Research Council. As you can probably gauge, it isn’t easy to get into Berkeley, unless you have an untouchable academic track record. And rightly so – some of the achievements at this institute are fantastic. To give you an idea, UC Berkeley and its researchers are associated with 6 chemical elements of the periodic table. Now that’s something, isn’t it?"},

    {:rank => 4, :university_name => 'California Institute Of Technology', :university_type => 'Private', :acceptance_rate => 9,
     :tuition => '$48,200', :location => 'Like you probably just read, Caltech is located in Pasadena, which fortunately is just about 18km away from downtown Los Angeles. Sounds like the Best of Both Worlds? Definitely.',
     :weather => 'Berkeley has a Mediterranean climate, though the temperatures in general are rather lower than what you come to expect in, say, Spain. Summers are cool and dry, while winters are cold and wet. Average temperatures in September (the ‘hottest’ month) are a high of 22.1°C and a low of 13.3°C, while average temperatures in January (the coldest month) are a high of 13.6°C and a low of 6.4°C. Berkeley also experiences rainfall once in a while, mainly during winters, and not much. Snowfall is a rare commodity, and normally takes place only on the peaks of hills.',
     :university_link => 'http://www.caltech.edu/', :university_desc => "The highly renowned California Institute of Technology is a private research university started in the year 1891. Located in Pasadena, Caltech has gained a reputation as one of the best technological institutes in the world. Understandably, it receives a massive number of applications from all over the world, including thousands from India. However, it isn’t easy to get in. In fact, Caltech is arguably one of the toughest universities to get into; call it bias, prejudice, or racism, Caltech just doesn’t seem to admit enough Indians. Though we think this perhaps has something to do with the extremely high levels of expectation here, and not much else."},

    {:rank => 4, :university_name => 'University of Michigan - Ann Arbor', :university_type => 'Public', :acceptance_rate => 25,
     :tuition => '$15,000', :location => 'University of Michigan is a 45 minute drive from Detroit, the main city of Michigan. Apart from the University, Ann Arbor is pretty boring but fortunately Detroit is quite accessible.',
     :weather => 'The one downside of studying at Ann Arbor could be the climate. It snows almost for 8-9 months of the year, making it terribly cold. During fall, you can expect to see sunrays once in a while which is a ‘feel good factor’ for students. It can get pretty gloomy most of the year.',
     :university_link => 'https://umich.edu/', :university_desc => "University of Michigan, Ann Arbor, is a public research university which was founded in 1817. UMich is very famous for its research work and has one of the largest research expenditures amongst American Universities.  It is one of the high ranking universities in the States, and thus it’s clearly not easy to get in. Many students still apply, though, putting it in the ‘ambitious’ category, and keeping their fingers firmly crossed."},

    {:rank => 6, :university_name => 'University of Texas at Arlington', :university_type => 'Public', :acceptance_rate => 55,
     :tuition => '$25,200', :location => 'As the name suggests, the university is situated in the large city of Arlington and the enormously huge state of Texas which is densely populated. Arlington is approximately 20 miles from the very famous Dallas and is the seventh largest city in Texas. Being a large city and surrounded by many institutions in the nearby vicinity, Arlington is generally preferred by students from all backgrounds.',
     :weather => 'Arlington is one of the cities in the US of A where you experience extremely hot summers. The Fall period i.e. July to early October, the climate is pretty hot and humid. Boys are generally seen in shorts and t-shirts while girls (hold your breath boys) don skirts/shorts and spaghettis. Arlington is not one of the places where the winters are something to look for. It snows rarely and is quite bearable yet Indians find it cold. Spring and autumn bring pleasant weather in the city.',
     :university_link => 'https://www.uta.edu/uta/', :university_desc => "Founded in 1895, University of Texas at Arlington fondly called as UT Arlington or UTA, is a public research university located in the state of Texas. Even though the university is part of the same group, ‘University of Texas’, the institution is ranked pretty low in the US of A. With the likes of the extremely ambitious Texas Austin and TAMU, followed by the hot favourite Texas at Dallas, Arlington looses out on the big league of Institutions. In spite of this, the college is preferred by a lot of Asians, especially Indians, with just an about average profile for Electrical and Telecomm courses majorly."},

    {:rank => 6, :university_name => 'Carnegie Mellon University', :university_type => 'Private', :acceptance_rate => 27,
     :tuition => '$47,600', :location => 'The main CMU campus is just 3 miles away from downtown Pittsburgh. Public transportation is the only means of commute for most of the students, but that isn’t really a problem since the public transport around here is pretty good. This provided you get used to the bus timings, of course. Also, CMU students can roam around most of Pittsburgh for free with the bus passes the university provides.',
     :weather => 'In a word, gloomy. There are very few days when the sky isn’t obscured by clouds. Summers are pretty humid, but never really hot. Winters, on the other hand, can get extremely cold. Pittsburgh experiences an appreciable amount of snowfall, and snowstorms aren’t uncommon.',
     :university_link => 'http://www.cmu.edu/', :university_desc => "Started in the year 1900, Carnegie Mellon University (CMU) is a private research university in Pittsburgh. It is one of the best colleges for just about any course, which is why it’s a ‘dream college’ for almost every Asian student. It’s pretty expensive, though, so that’s something you have to keep in mind."},


    {:rank => 7, :university_name => 'Purdue University West Lafayette', :university_type => 'Public', :acceptance_rate => 23,
     :tuition => '$31,000', :location => 'West Lafayette, by itself, is at best a college town. It tends to get pretty boring in the immediate surroundings of Purdue, but fortunately Indianapolis is just 70 or so miles away, and you can drive to Chicago and Cincinnati in a couple of hours.',
     :weather => 'It’s rather awful, to be honest, so if random change of climate doesn’t exactly suit you, you should probably stay away from Purdue. The weather changes on a weekly basis – there could be a snowstorm one week, and it could become warm and humid the next. Summers are warm and winters are terribly cold, but there isn’t much differentiating which comes when.',
     :university_link => 'http://www.purdue.edu/', :university_desc => "Started in 1869, Purdue University is a public research university located in West Lafayette, Indiana. It is one of the highest-rated universities in the USA, and rightly so. It is involved in very high levels of research, and has some of the best academic programs to offer. Before you read any further, you ought to know that you need an absolutely mind-boggling profile to get into Purdue. An extremely high GPA, some excellent research work, and a couple of international technical papers can give you a chance of making it to Purdue. Note how we say ‘can’ and not ‘will’ – it really is that hard. To get an idea, even IITians with breathtakingly good profiles find it difficult to get in."},


    {:rank => 8, :university_name => 'Georgia Institute of Technology', :university_type => 'Public', :acceptance_rate => 31,
     :tuition => '$28,000', :location => 'Georgia Tech is located in the beautiful city of Atlanta in Georgia. Now, the institute is more or less part of a ‘student village’, which means that there isn’t really too much in the place apart from the colleges.Fortunately, Atlanta itself is a pretty big city and a really cool place to be in, so students don’t really have to step out much. And that’s a good thing, because there aren’t really any ‘major cities’ around.',
     :weather => 'Atlanta (where Georgia Tech is) has a humid subtropical climate, which means it has extremes of temperatures across the year. Summers are hot and humid, while winters are very cold. The coldest month is normally January, where the average temperature is about 6°C, although temperatures often fall to about -7°C at night. July is normally the warmest month, and temperatures can go as high as 36°C, with 31°C being the average. Atlanta does not receive a terribly high amount of snowfall in spite of the low temperatures, but rainfall occurs almost throughout the year, though it’s never exactly ‘torrential’.',
     :university_link => 'http://www.gatech.edu/', :university_desc => "Georgia Institute of Technology, more commonly known as Georgia Tech, is one of the most reputed public research universities in the world. Founded in 1885, GeorgiaTech initially started with core programs like mechanical, civil and aerospace engineering. But in the early 1900s, it started a host of other programs, and now is highly reputed for ALL of its courses as well. Another thing to be known about Georgia Tech is the fact that it has ‘satellite campuses’ in France, Ireland, China (Shanghai) as well as Singapore. Students are often given options of specialized programs wherein they spend one year at the main GT campus and another year at one of the foreign campuses."},

    {:rank => 9, :university_name => 'North Carolina State University, Raleigh', :university_type => 'Public', :acceptance_rate => 17,
     :tuition => '$26,400', :location => 'NCSU is located in Raleigh, which is the capital city of North Carolina. Raleigh is one of the fastest-growing cities in the country and the city of Raleigh is named after Sir Walter Raleigh, who established the lost Roanoke Colony in present-day Dare County.',
     :weather => "NCSU main campus has three sub campuses, North, Central and South. Although your life would be pretty much centered around the Engineering buildings (which is in the wonderful centennial campus), you should definitely take a few long walks around the rest of the campus, because well, it’s quite breathtakingly beautiful. Added to the fact that all the libraries, laboratories and research centers are state-of-the-art, and you get the perfect ‘university feel’. The gym, recreation center and the sports/athletic facilities are great as well. The brand new Hunt Library is certainly one of the most amazing structures you'll ever see, magnificent and hi-tech, it is the world’s first artificial intelligence involved library.",
     :university_link => 'https://www.ncsu.edu/', :university_desc => "North Carolina State University (NCSU) is a public research university started in 1887. It has an enrollment of over 30,000 students, making it the largest university in Carolina by a margin. NCSU is especially well known for programs like ECE, CSE and Computer Networking (which is offered in very few other universities), and this fact coupled with its low tuition fees makes it a dream college for many students. It ranks #217 according to U.S. News' 'Best Global Universities Ranking' list."},

    {:rank => 9, :university_name => 'University of Illinois at Urbana-Champaign', :university_type => 'Public', :acceptance_rate => 26,
     :tuition => '$34,400', :location => 'As you probably figured out, UIUC is located in the twin cities of Urbana and Champaign, in the state of Illinois. While there isn’t too much to say about the immediate location, UIUC is fortuitously just about 3 hours or so away from Chicago, which is a common weekend ‘retreat’ back to civilization for students.',
     :weather => "Urbana-Champaign is infamous for its frankly awful and unpredictable weather. Winters are biting cold and summers can get pretty hot. Most students carry an umbrella or a raincoat around at most times, since it can rain any time of the year. The twin cities receive ample amount of snowfall in winters, and students walking into class semi-frozen isn’t an uncommon sight.",
     :university_link => 'http://www.illinois.edu/', :university_desc => "University of Illinois – Urbana Champaign is a public research university, started in 1859. Because of its glorious history and excellent opportunity, it is widely regarded as the best public university in the States. That was the good news. The bad news is that it’s awfully hard to get into UIUC, and next to impossible for Indians, unless they have fantastic profiles. No no no, it’s not racism. It’s just that, well, people tend to have better profiles than the average Indian."},

    {:rank => 10, :university_name => 'University of Southern California', :university_type => 'Private', :acceptance_rate => 23,
     :tuition => '$32,100', :location => 'The University Park Campus of USC is in the West Adam’s district of South Los Angeles. The campus is within walking distance from LA Coliseum and Staple Centre, House of the LA Lakers.',
     :weather => "Weather at the Southern California is pretty decent as there is enough sunlight during the day time which makes it sufficiently hot while the nights are cool enough to bear the weather. Fall period is quite hot while rain showers are the standard customers during winter.",
     :university_link => 'http://www.illinois.edu/', :university_desc => "The University of Southern California is a private research University which was founded in 1880, making it California’s oldest private university. USC is involved in very high level research activity and thus has quickly risen up the ranking.  It may interest you that although USC claims that their students hail from 112 countries, but it feels a lot like India once you’re there."},

    {:rank => 10, :university_name => 'University of Texas at Austin', :university_type => 'Public', :acceptance_rate => 17,
      :tuition => '$13,000', :location => 'As the name quite clearly suggests, the University of Texas at Austin is located at, well, Austin in Texas. Being the ‘live music capital’ of the world, Austin witnesses a massive number of concerts week in week out. It’s a nice, laid-back place, where the major modes of transport are bikes, cabs or just foot. Shuttle buses are available within the university, though.  Most graduate students live off-campus, because it’s cheaper and you get a little more freedom (though Indians wouldn’t be used to even the on-campus levels of freedom; they stay off-campus only for one reason). Three major off-campus options are West Campus, North Campus and Riverside, of which West is quite expensive. The other two are slightly more affordable, but they’re further away from the UTA campus. Of course, one should also take into consideration the appreciable crime rate when renting a house in Austin. It’s not that bad, really, but things do happen.',
      :weather => "Austin, Texas experiences nine months of summer, two months of fall, and just a solitary month of winter. Although the weather is unpredictable, the winters aren’t really cold. Summers can get really hot though.",
      :university_link => 'http://www.utexas.edu/', :university_desc => "Founded in 1885, University of Texas at Austin is one of the most prestigious schools in the USA. It is a public research university, and is the flagship institute of the University of Texas System. UTA is a dream university for a number of students thanks to its history, and the excellent future it promises. However, it isn’t an easy task to get in, unless you have an absolutely outstanding profile, complete with impeccable academics, a couple of international publications, and extensive research work."},

    {:rank => 12, :university_name => 'Texas A&M University, College Station', :university_type => 'Public', :acceptance_rate => 24,
     :tuition => '$12,000', :location => 'Well, it’s not that great, really! Located at College Station, TAMU is the sole attraction of the city. Fortunately, all of Houston, Austin and Dallas are within about three hours from TAMU.',
     :weather => "The weather, like in the rest of Texas is pretty hot and humid. Summer temperatures can be as high as 40 degree Celsius while winters are much cooler. College Station occasionally receives some snowfall, but what really troubles you in winters is the biting cold breeze.",
     :university_link => 'http://www.tamu.edu/', :university_desc => "Texas A&M University, fondly called as TAMU, is a public research university founded in 1876. It is one of the best universities in the States as the research work and the opportunities opening after Graduation is spell bounding. Although applying to TAMU is nothing short of Ambitious, you stand a decent chance if you have an excellent research work and International papers to back your application. TAMU is a dream college for IITians and NITians."},

    {:rank => 12, :university_name => 'Columbia University', :university_type => 'Private', :acceptance_rate => 22,
     :tuition => '$26,000', :location => 'Columbia University is located in the tremendously upmarket Manhattan district of New York. There’s really nothing else to say, is there? Manhattan! THE Manhattan!The subway station and a major bus stop are right outside the gate of Columbia University, so travelling is pretty convenient for all students, regardless of where they stay.',
     :weather => "In spite of New York’s proximity to the Atlantic Ocean, the city does tend to have somewhat extreme climate; the summers are warm and the winters are cold. Temperatures in winter can fall as low as -10°C during nights, and in summer can go as high as 34°C during the afternoon. New York receives a fair share of rainfall, especially during spring.",
     :university_link => 'http://www.columbia.edu/', :university_desc => "The Fu Foundation School of Engineering of the Columbia University is a private research institute started in 1896. The fifth-oldest university in the United States, CU has achieved Ivy League status thanks to its standing amongst the elite. It is one of the more sought-after schools around, but it isn’t impossible to get in, provided your academics are more-than-decent, and you’ve done a fair share of some kind of research work."},

    {:rank => 12, :university_name => 'University of California, San Diego', :university_type => 'Public', :acceptance_rate => 22,
     :tuition => '$25,000', :location => 'UCSD, contrary to what the name might suggest, is not located in the centre of San Diego, but LA Jolla is a short drive from Downtown San Diego which is a good place to hang around. It’s around 26 miles from Tijuana, Mexico and within 100 miles of Los Angeles and Long Beach.',
     :weather => "The climate of San Diego is classified as semi arid or Mediterranean, which in a nutshell means that it’s pretty pleasant. Fortunately, the climate is moderate and the temperatures don’t fluctuate too much. Average monthly temperature ranges from 14 degree C to 23 degree C. UCSD doesn’t experience rainfall and snowfall. You will often see students wearing shorts and hoods or t-shirts.",
     :university_link => 'http://ucsd.edu/', :university_desc => "The University of California, San Diego is a public research university founded in 1960 in the La Jolla neighbourhood of San Diego. Students with an average profile should know that it’s not easy to get in UCSD. Asians, especially Indians, aim for this university primarily for two reasons:  1. California 2. Public University (read ‘low tuition fee’)"},

    {:rank => 15, :university_name => 'University of North Carolina at Charlotte', :university_type => 'Public', :acceptance_rate => 45,
     :tuition => '$19,000', :location => 'Located in the second largest banking sector of the States, Charlotte is the largest city in the state of North Carolina. Though students usually dream to get an admit from the elder brother NCSU, UNCC is one of the colleges in the USA or probably any part of the nation, which is hugely famous for thousands of business start ups. Thanks, to its location and the best financial background.  Nicknamed the Queen City, Charlotte is located several miles east of the Catawba River and southeast of Lake Norman, the largest man-made lake in North Carolina.',
     :weather => "Charlotte, like other southeastern states has a humid subtropical climate. Winters are short and generally mild while the summers are extremely warm and humid. Though snowfall is rare, students are pretty happy with the climate from late November to January. The only advantage at Charlotte in terms of climate is that it never experiences extreme temperatures.",
     :university_link => 'https://www.uncc.edu/', :university_desc => "University of North Carolina at Charlotte, usually referred as UNCC or simply Charlotte, is a public research university founded in 1871. The university is pretty famous for its Electrical Engineering and Computer Science programs and is always on the application list of an average profile. UNC of Charlotte is a hot favourite university for Asians, especially Indians, considering the strategic location and easily affordable fees. Note: UNCC is not to be confused with University of North Carolina-Chapel Hill and the latter is any day a notch above the former."},

    {:rank => 15, :university_name => 'Cornell University', :university_type => 'Private', :acceptance_rate => 28,
     :tuition => '$54,600', :location => 'While Ithaca by itself is pretty much just a college town, Cornell does have the advantage of being somewhat strategically located. Toronto (Canda), New York City and Philadelphia are all within a 3-4 hour radius.',
     :weather => "Oh, the weather is quite awful. If the hot and humid summers aren’t enough to frustrate you, the cold, snowy winters will definitely make you very gloomy indeed. What’s more, there’s a lot of rainfall spread across the year to dampen your otherwise excellent college experience.",
     :university_link => 'https://www.uncc.edu/', :university_desc => "Cornell University is a private research university located in Ithaca, in the state of New York. Founded in 1865, the college is an Ivy League university, and rightly so – Cornell is, without doubt, one of the finest universities in the USA, if not the world. And since it’s one of the finest, it’s also one of the toughest universities to get into. You’ll find thousands of students applying to Cornell hopefully, only to see their applications being rejected. This doesn’t normally dishearten anyone, though – most people expect it, and those who don’t, well, aren’t terribly smart and definitely don’t deserve to get into Cornell anyway."},

    {:rank => 16, :university_name => 'University of California, Los Angeles', :university_type => 'Public', :acceptance_rate => 29,
     :tuition => '$32,000', :location => 'Like the name suggests, the university is located in the very posh city of Los Angeles. It’s about 5 miles from the ocean and pretty close to the Getty Center. The postal address says it’s in Westwood Village, although nothing about the place seems like a village. It’s a lovely student town, with a million things to do nearby. There’s Hollywood, Beverly Hills and Disneyland almost next door, so all you star-struck people out there should definitely try getting into UCLA.',
     :weather => "Well, California is known for its climate, and Los Angeles epitomizes everything that is good about California. Most days are sunny, and LA receives rainfall roughly 30 days a year. The average annual temperature is about 20°C, and it barely ever goes more than 5°C here or there the entire year. There’s no snowfall, and the weather on a whole is quite pleasant.",
     :university_link => 'http://www.ucla.edu/', :university_desc => "University of California – Los Angeles is a public research university founded in 1919. It’s amongst the top universities in the USA, and is a hot favourite among Asians (specially Indians) although it should be noted that it’s not easy to get in at all.  While UCLA is naturally renowned because of its excellent academic programs, that’s not the only thing it’s famous for. A hair-raising statistic about UCLA is its Olympic tradition – the university has had at least one gold medalist in each and every Olympics since 1920."},

    {:rank => 17, :university_name => 'Princeton University', :university_type => 'Private', :acceptance_rate => 11,
    :tuition => '$49,500', :location => 'Princeton is located in a town which is its namesake in the state of New Jersey. There are numerous other organizations which have their Head Quarters in the “college town”. New Jersey itself is a very bustling place with a lot of industrial development and is known to have maximum number of millionaires in the States. For those who don’t know New Jersey or as many would like to say NJ, it is the neighbouring state to the much famous New York and has truckloads of Indians especially Gujaratis.',
    :weather => "Incessant rain is a common feature of the weather at Princeton. There is a lot of humidity as a result and an unpleasant stickiness. In time you will ultimately learn to get used to it. Some are even of the opinion that the weather is highly varying with unpredictable changes. During other seasons it’s a regular sight to see large groups of people hanging around barbeques and chilling in groups.",
    :university_link => 'http://www.princeton.edu/', :university_desc => "Princeton University is a Private Ivy League research university founded in the year 1746. It was set up by the British colonial rulers even before America could gain independence. Over the years, Princeton has gone on to produce students who have gone on to become world leaders, great scientists and inventors. It is, arguably, one of the best universities across the planet. All these reasons have led to Princeton having an ultra-low intake level, so we guess most of y’all are reading this review purely for knowledge and entertainment sake. Jokes apart, every top ranker from the top Indian or Asians universities keeps Princeton as a dream option which means the chances of an admit are next to zero, of course."},

    {:rank => 18, :university_name => 'Pennsylvania State University', :university_type => 'Public', :acceptance_rate => 30,
     :tuition => '$34,000', :location => 'Penn State is located in University Park in Pennsylvania which is a rather rural area. There isn’t too much to do around the campus, and life can get boring, so to speak. University Park Airport is supposedly the only good location in the entire area. Apart from the main campus of the Pennsylvania State College, the next well know place would be the city of Pittsburgh.',
     :weather => "The climate of Pennsylvania is pretty severe. Winters are extremely cold with snowfall almost every minute. The roads are extremely wet and commutation becomes a problem. The temperatures fall as low as -15 degrees Celcius. Summers are bearable, but seem bloody hot when compared to the awful winters. On a whole, the weather at Penn State is something you would not look for.",
     :university_link => 'http://www.psu.edu/', :university_desc => "Pennsylvania State University, commonly referred to as Penn State or PSU, is a public research university which was started in 1855 in the state of Pennsylvania, USA. Penn State is a high ranked college and is often considered as a Public Ivy League in America. Since it’s an ambitious public university, it’s a hot favourite among Asians, especially Indians, as the tuition fee is quite affordable. Having said that, it’s quite difficult to make it to this university considering the number of applicants they get here."},

    {:rank => 18, :university_name => 'University of Pennsylvania', :university_type => 'Private', :acceptance_rate => 23,
     :tuition => '$30,000', :location => 'University of Pennsylvania is located in the city of Philadelphia, just across the Schuylkill River from Center City. Pennsylvania is conveniently close to New York City and Washington DC, and pretty accessible by trains and buses, though one can obviously not make travelling a daily affair.',
     :weather => "Philadelphia experiences extremes of climate. Summers are typically hot and muggy, fall and spring are generally mild, and winter is cold. Snowfall is variable, with some winters bringing only light snow and others bringing several major snowstorms. The January (coldest month) average is 32.3 °F (0.17 °C), though lows at times reach 10 °F (?12 °C), and highs may soar above 50 °F (10 °C). July (hottest month) averages 77.6 °F (25.3 °C), although heat waves accompanied by high humidity are frequent with highs above 95 °F (35 °C). Early fall and late winter are generally driest, with October being the driest month.",
     :university_link => 'http://www.upenn.edu/', :university_desc => "University of Pennsylvania is located in the city of Philadelphia, just across the Schuylkill River from Center City. Pennsylvania is conveniently close to New York City and Washington DC, and pretty accessible by trains and buses, though one can obviously not make travelling a daily affair."},

    {:rank => 18, :university_name => 'John Hopkins University', :university_type => 'Private', :acceptance_rate => 24,
     :tuition => '$50,500', :location => 'A major reason why JHU is what it is, is probably its absolutely fantastic location. Baltimore is a mid-sized city, but there are a million things you can do here. And although you’ll definitely find enough to keep you busy, you can always make the short trip to Washington DC, or the slightly longer trip to Philadelphia.',
     :weather => "Baltimore has a ‘subtropical’ kind of climate. But without getting into details of what that means, let’s just say that Indians won’t like it too much here. Winters get awfully cold, and summers don’t really do justice to the word ‘warm’, by Indian standards. The average July (hottest month) temperature is about 24 degrees Centigrade, while it’s quite common for winter temperatures to go well beyond the zero mark. Rainfall occurs throughout the year, though it’s never really torrential. Winters experience some amount of snowfall, and it’s advised to carry a good few layers of clothing.",
     :university_link => 'https://www.jhu.edu/', :university_desc => "Johns Hopkins University (JHU) is a private research university located in Baltimore, Maryland. Consistently ranked as one of the top universities for research in the world, JHU is a universal favourite for its medical, biotech engineering and biomedical engineering programs. A little fun fact – more than 33 Nobel Prize winners are in some way associated with the university, either past/present professors or alumni."},

    {:rank => 20, :university_name => 'University of Wisconsin-Madison', :university_type => 'Public', :acceptance_rate => 11,
     :tuition => '$15,000', :location => 'Madison is a mid-sized, more or less quite city and is home to a number of universities. Of course, UW is highest ranked amongst these, and is rightly given one of the best possible locations in the city. The university is more or less self-sufficient, though there are a number of bars and restaurants nearby anyway. And you can obviously make the short two hour drive to Chicago if you need to.',
     :weather => "To put it subtly, you would have seen better weather. Summers are pretty hot, and you’re going to need a good amount of sunscreen. Winters, conversely, are terribly cold, with temperatures often falling well below the zero mark. Madison receives around 100 inches of snow every year which, in case you didn’t know, is quite a bit.",
     :university_link => 'http://www.wisc.edu/', :university_desc => "The University of Wisconsin Madison is a public research university, and is the flagship institute of the University of Wisconsin system. Founded in 1848, the school ranks among the top ten for a number of its programs, including many in various forms of engineering. Of course, this also means that it’s quite a big ask for an average human to get in, but if you have a good enough profile, then it’s definitely worth a shot."},

    {:rank => 20, :university_name => 'Northwestern University', :university_type => 'Private', :acceptance_rate => 23,
     :tuition => '$48,000', :location => 'Even though Evanston does have the distinction of being categorized as a city, it might as well just have been part of Chicago, which is just 13 miles away. Clearly, with Chicago next door, you have just about everything you could possibly ask for under the sun.',
     :weather => "It’s probably not the kind of climate that you’re used to, and the first few months might be a task, but people get used to the Chicago weather pretty quickly. All four seasons are distinctly represented, and distinctly different. Summers can get hot and humid, with temperatures between 26 degrees and 33 degrees Celsius. Winters, on the other hand, are pretty cold, with temperatures often going subzero, and an appreciable amount of snowfall. Autumns are perhaps the best time of the year, with just about perfect temperature, though it rains more or less throughout the year. Don’t be too much by the ‘Windy City’ moniker though – there are many cities far windier than Chicago – you won’t be flying without an air ticket.",
     :university_link => 'http://www.northwestern.edu/', :university_desc => "Northwestern University is a private research university founded in 1851. While the campus is somewhat divided into two halves (the Evanston campus and the Chicago campus), we’re only going to talk about the one at Evanston, since that’s where all engineering students are going to end up. Now while Northwestern is known for the very excellent Kellogg School of Management, it’s important to know that just about every other area of study at the university is quite a handful as well."},

    {:rank => 22, :university_name => 'University of Maryland, College Park', :university_type => 'Public', :acceptance_rate => 25,
     :tuition => '$29,000', :location => 'Located between Washington, D.C., and Baltimore, the University of Maryland offers students a suburban lifestyle within easy reach of big-city experiences. The flagship campus in College Park, which has its own subway stop on the D.C.-area Metro transit system, is often considered a commuter school. There are a lot of things to do as far as recreation is concerned. Southern Maryland has the Chesapeake Bay where there is fishing, crabbing, boating, jet skiing, windsurfing, and hunting. There are a lot of shopping malls, parks, and restaurants. Annapolis has a lot of night clubs and is close to Washington DC. The cost of living however is way too high.',
     :weather => "Being at the western edge of Atlantic coastal plain, College Park has a humid subtropical climate. Summers are warm and humid with the hottest month being July with 30-degree Celsius. Rains are frequent during summers. Winters are mild with the coldest temperature being 7-degree Celsius. Springs and autumn are particularly pleasant.",
     :university_link => 'http://www.umd.edu/', :university_desc => "University of Maryland College Park (UMCP) is a public institution that was founded in 1856. Its setting is suburban, and the campus size is 1,250 acres. The University of Maryland has highly ranked graduate programs in education (top 30 universities in USA) and the noted A. James Clark School of Engineering (ranked at #22 on US News Rankings), as well as well-regarded offerings through the Robert H. Smith School of Business. The university regularly earns accolades for its sustainable and clean energy initiatives, such as its plan to be carbon neutral by 2050 and campus-wide efforts to compost dining hall waste."},

    {:rank => 22, :university_name => 'Harvard University', :university_type => 'Private', :acceptance_rate => 10,
     :tuition => '$46,400', :location => "Home to two of America's most prestigious universities, Cambridge exudes a certain intellectual quirkiness. A mix of historical haunts, student hang-outs, alternative art and culture venues, vintage clothing shops, bookshops and ethnic restaurants, the city is, well, really cool. Although it is located just across the Charles River from Boston, Cambridge has a distinct vibe that is noticeable immediately.",
     :weather => "Cambridge, MA climate is warm during summer when temperatures tend to be in the 70's and very cold during winter when temperatures tend to be in the 30's.The warmest month of the year is July with an average maximum temperature of 82.20 degrees Fahrenheit, while the coldest month of the year is January with an average minimum temperature of 22.10 degrees Fahrenheit. Temperature variations between night and day tend to be fairly limited during summer with a difference that can reach 16 degrees Fahrenheit, and fairly limited during winter with an average difference of 14 degrees Fahrenheit. Rainfall in is fairly evenly distributed throughout the year. The wettest month of the year is November.",
     :university_link => 'http://www.harvard.edu/', :university_desc => "Harvard University is a private Ivy League research university in Cambridge, Massachusetts, established 1636. Its history, influence and wealth have made it one of the most prestigious universities in the world."},

    {:rank => 24, :university_name => 'University of California, Santa Barbara', :university_type => 'Public', :acceptance_rate => 14,
     :tuition => '$28,000', :location => "UCSB is at one of the best possible locations for a university, owing to the laid-back atmosphere of Santa Barbara, combined with its proximity to some of the busiest cities in the US. Santa Barbara is a popular holiday destination for many tourists, because of the splendid weather and picturesque beauty. Los Angeles is an hour and a half to the South, San Francisco is five hours North, San Diego is four hours South, and the wine country is half an hour inland.",
     :weather => "Santa Barbara experiences a cool Mediterranean climate characteristic of coastal California. Because of the city's proximity to the ocean, on-shore breezes significantly moderate temperatures, resulting in warmer winters and cooler summers. It is normally sunny throughout the year, with occasional rainfall once in a while. The average temperature over the year is about 15°C, with the maximum high and low not going too far above or below that mark.",
     :university_link => 'http://www.ucsb.edu/', :university_desc => "University of California – Santa Barbara is a public research university founded in 1905. Any student with an inherent desire to ‘chill’ should definitely put UCSB at the top of his wish-list. A perfect combination of location, climate, teaching, crowd and nightlife ensures that no one would ever regret going to Santa Barbara."},

    {:rank => 26, :university_name => 'University of Washington', :university_type => 'Public', :acceptance_rate => 20,
     :tuition => '$41,400', :location => "Seattle, majorly located around the coast, is the largest city in the Pacific Northwest region of North America. Over the last couple of decades, the city has shown tremendous improvement in the technology and internet sector. There are ample places to eat and drink in the university vicinity area and also throughout the city. Downtown Seattle, Pike Place Market, and the Space Needle attract many people; local events like the Bumbershoot Festival and neighborhood parades and fairs make weekends all the more unique. All in all, the location gets a thumbs up despite not as famous as California and New York.",
     :weather => "Seattle's climate is usually described as oceanic or temperate marine, with mild, wet winters and warm, dry summers. It rains for most part of the year keeping the surroundings wet and green. Moreover, weather is extremely cloudy. As expected, students from the Asian countries, primarily India, find the climate VERY cold at Seattle. We really wonder what’s their take on New York, Michigan and Boston?",
     :university_link => 'https://www.washington.edu/', :university_desc => "Founded in 1861, University of Washington is one of the oldest universities on the North West Coast of the United States of America. UW, commonly referred, is a public research university in the city of Seattle and is also labelled as a part of the Public Ivies (comparable to Ivy League institues). It is somehow not one of the favourite institutions on an Asian, especially Indian, applicants list mainly because of its low acceptance rate. Well known for its core courses especially Electrical, Computer and Mechanical/Aerospace Engineering, University of Washington is one of the high ranking institutions and thus requires a commendable profile to get admitted."},

    {:rank => 26, :university_name => 'Duke University', :university_type => 'Private', :acceptance_rate => 28,
     :tuition => '$27,900', :location => "Readers should know that when we say Durham, it’s not to be mistaken for the Durham in England, of course. Although it’s one of the bigger cities in North Carolina, it’s quite dull, really, and there isn’t too much to look forward to even around Durham. Raleigh is about half an hour away, but the nearest ‘big’ city would be Washington DC, and that’s a good 5-6 hours away. Oh dear.",
     :weather => "If you like the Mediterranean climate, Durham is certainly not the place for you. Hot and humid summers are awfully complemented by cold, snowy (by Indian standards, at least) winters. The couple of months of rain will leave you wishing for a drought next year, but that won’t happen anyway. All in all, it’s not too great, but students say that it’s worth the pain, because Durham looks absolutely breathtaking when Mother Nature chooses to be nice.",
     :university_link => 'http://www.duke.edu/', :university_desc => "Duke University is a private research university located in Durham, North Carolina. While certainly more popular for its management and medical courses, Duke is quite a handful even when it comes to engineering, and certainly ranks amongst the top 50 for all the fields if offers. That, if you’re wondering, is pretty good."},

    {:rank => 28, :university_name => 'University of Minnesota, Twin Cities', :university_type => 'Public', :acceptance_rate => 24,
     :tuition => '$16,000', :location => "Although University of Minnesota is pretty much a city by itself (they have bars, cafes, coffee shops, everything!), there’s also a lot to do in the twin cities of Minneapolis and St Paul. Since the college is right next to Downtown, students are just a short bus ride away from a plethora of time-wasting opportunities. Of course, you can also go hiking, or take a bike-ride by the lake. There’s plenty to do, but there’s not much more once you get out of the twin cities. The nearest ‘big’ city would probably be Kansas City, and that’s a good 400 miles away.",
     :weather => "Oh, it’s terrible. Winters in the Twin Cities are biting cold, and the worst part about them is that they never seem to get over. It’s perfectly normal to witness snowfall during spring break, and even when ‘summer’ does come along, it just doesn’t manage to stay. A couple of feet of snow isn’t considered odd during winters, so you can imagine how bad it would be. All in all, the weather here isn’t meant for everyone, and it’s common for students to fall sick and go into depression because of the general gloominess. It’s highly advisable to get LOTS of clothes, so that you can dress up in layers on a daily basis (yes, you’ll need to).",
     :university_link => 'http://twin-cities.umn.edu/', :university_desc => "The University of Minnesota, Twin Cities (U of M) is a public research university located in Minneapolis and St. Paul, Minnesota, United States. It is the oldest and largest campus within the University of Minnesota system and has the fourth-largest student body in the United States, in terms of numbers. It’s also a fantastic university, which is quite clear when you consider how hard it is to get into it."},

    {:rank => 29, :university_name => 'Ohio State University', :university_type => 'Public', :acceptance_rate => 18,
     :tuition => '$30,000', :location => "Columbus is a small town in Ohio, and to be honest, there isn’t too much near it either. Cincinnati is about 100 miles away, and it’ll take you 4-5 hours to drive to Pittsburgh or Detroit, the ‘big cities’ nearby.",
     :weather => "Oh it’s quite terrible. Even if you go live in the Himalayas for a few months and acclimatize yourself to the biting cold, you would never be able to prepare yourself for the horrible tornadoes, with speeds of upto 90kmph, that often hit Columbus. The weather is extremely unpredictable and unfriendly, showing insane amounts of yearly, and even daily, fluctuations in rainfall, temperature and snowfall. In a nutshell, hope for the best and prepare for the worst.",
     :university_link => 'http://www.osu.edu/', :university_desc => "Ohio State University is a public research university located in Columbus, which is, obviously, in the state of Ohio. Founded in 1873, OSU is the third largest university campus in the United States of America. OSU is considered one of the better universities when it comes to Computer Engineering and also Networking."},

    {:rank => 30, :university_name => 'Virginia Tech', :university_type => 'Public', :acceptance_rate => 23,
     :tuition => '$22,000', :location => "A common complaint about VirginiaTech is that, well, it doesn’t have much of a location. In spite of the massive student population, Blacksburg is a tiny town, with not much to do at all. The size and location of the place makes students wonder if they’re in the middle of nowhere. Christiansburg is the closest major city nearby, though students hailing from bigger cities often question its ‘major-ness’. But you eventually take a liking to the place, we’ve been told. An added advantage, of course, is the fact that Blacksburg is pretty safe, and you can move about freely.",
     :weather => "Well, it’s pretty bad. Blacksburg experiences terribly unpredictable weather; students say that you often experience all four seasons on the same day! Students dress in layers, because the weather can change drastically from morning to afternoon. Winters are biting cold, though you rarely experience very heavy snowfall. Summers are warmer, but nights are pretty cold. It rains almost throughout the year, and is extremely unpredictable, so you should probably be carrying your raincoat around.",
     :university_link => 'http://www.vt.edu/', :university_desc => "Although most students would fail to identify with it, the real name of ‘VirginiaTech’ is Virginia Polytechnic Institute and State University. It’s a public ‘land-grant’ university in Blacksburg, Virginia, and has been one of the top universities in the country ever since its inauguration in 1872. VirginiaTech is one of the most sought after colleges around, especially for students pursuing a Masters in branches like Mechanical, Civil, and Aerospace Engineering. Getting in is extremely difficult though – every year the average undergrad GPA increases, and the number of applications shoots up some more."},

    {:rank => 30, :university_name => 'Rice University', :university_type => 'Private', :acceptance_rate => 21,
     :tuition => '$32,000', :location => "Houston, where Rice University is located is America's fourth-largest. This city is a cosmopolitan destination, filled with world-class dining, arts, hotels, shopping and nightlife. Take a stroll through the historic heights; spend the day exploring the Museum District or head down to Space Center Houston. Later on, grab a bite in one of dozens of award-winning restaurants, or hang out with the cool kids on Washington Avenue. There's always something to do in this Southern hospitality meets urban chic city. Now coming to the cons - the traffic, the oppressive heat and humidity, the zoning free areas and nasty locals are common issues people living in Houston have to put up with.",
     :weather => "The Climate of Houston is humid subtropical. August normally ranks as the warmest month at 84.6 °F (29.2 °C) and January the coldest month at 53.1 °F (11.7 °C). Occasional severe weather of Houston mostly takes the form of flooding. Supercell thunderstorms sometimes bring tornadoes to the area, most commonly during spring. Houston sometimes experiences tropical cyclones during the Atlantic hurricane season, which can bring heavy rain and significant damage to the city. The last hurricane to hit was Hurricane Ike in 2008.",
     :university_link => 'http://www.rice.edu/', :university_desc => "Rice University, a privately endowed, nonsectarian, coeducational institution, was founded in 1891 as the William Marsh Rice Institute, dedicated to the advancement of letters, science, and art. The university occupies a 300-acre tree-lined campus located one block northwest of the Texas Medical Center and approximately three miles southwest of Houston's central business district. Engineering has been a part of Rice's curriculum since the university first opened as The Rice Institute in 1912. In those early days Rice offered courses in chemical, civil, mechanical and electrical engineering. Over the years, the engineering program grew, and in 1975 the George R. Brown School of Engineering was established. Today the school is comprised of nine academic departments and includes seventeen research institutes and centers."},

    {:rank => 32, :university_name => 'University of Colorado Boulder', :university_type => 'Public', :acceptance_rate => 38,
     :tuition => '$30,000', :location => "University of Colorado, Boulder is literally in the centre of USA. Although the university is located in what can be called like a village kind area, it is just one hour from Denver. This really adds to the value of the university since Denver is arguably the Telecom capital of the world. The surroundings of the university are absolutely picturesque. There are hills right behind the university and the sky looks resplendent when it rains.",
     :weather => "Since Colorado is centrally located, it often experiences rather extreme temperatures. Winters are quite cold with the occasional snowfall while the summers are pretty warm. You often witness thunderstorms in Colorado as well. Sunshine is expected probably every morning as you can expect sunlight to be there for at least 8-10 months of the year.",
     :university_link => 'http://www.colorado.edu/', :university_desc => "The University of Colorado at Boulder is a public research university. Started in 1876, it is one of the most popular public universities and the telecomm program it offers is probably the oldest and definitely the finest in the world! It is especially popular among Asians."},

    {:rank => 33, :university_name => 'University of California, Davis', :university_type => 'Public', :acceptance_rate => 21,
     :tuition => '$28,000', :location => "Davis really does have the best of both worlds. While it’s more or less a college town by itself, Sacramento is right next door, while Oakland, San Francisco and San Jose aren’t too far either. All in all, an excellent location and a good place to live in.",
     :weather => "A very simple rule. If it’s California, the weather must be good. And it is just that – pleasant throughout the year without getting unreasonably warm or cold, Davis is an absolute joy to live in.",
     :university_link => 'http://www.ucdavis.edu/', :university_desc => "University of California, Davis is a public research university located in the college town of Davis. Established in 1905, it is consistently ranked among the top universities in the world. For whatever unknown reasons, though, it gets rather step-brotherly treatment in the field of engineering compared to its Berkeley and Los Angeles counterparts. It is, however, an excellent university, and definitely one that should be given consideration to."},

    {:rank => 35, :university_name => 'Boston University', :university_type => 'Private', :acceptance_rate => 25,
     :tuition => '$52,900', :location => "As the name quite clearly suggests, the institute is located at Boston, Massachusetts. Boston is one of the busiest cities in the world, but that doesn’t mean that people are working round the clock. It’s one of those cities where, if you’ll forgive the use of the cliché, people ‘work hard and party harder’.",
     :weather => "As is the case in many excellent institutes, Boston University has some professors who can directly alter the course of your life. In a good way, of course. While most of the professors can comfortably be categorized as ‘well above average’, there are some who just fall under the ‘mind blowing’ category. Often you may find yourself wanting to take up a particular course/subject purely and solely because a particular professor would be tutoring you. Hopefully that’ll be for academic and not aesthetic reasons.",
     :university_link => 'http://www.bu.edu/', :university_desc => "Boston University (BU) is a private research university which got its name in 1869. In the city of Boston, which is famous for being a college city bustling with student life, BU is one of the more recognized universities. It is a students’ favourite, because of several factors – the quality of education, the quality of life, and the quality of women. All this combined with the fact that it isn’t exactly impossible to get in."},

    {:rank => 35, :university_name => 'University of California, Irvine', :university_type => 'Public', :acceptance_rate => 20,
     :tuition => '$27,000', :location => "Irvine has popularly been voted as one of the best places to live in the United States. A part of Orange County (OC, for those of you obsessed with the show), Irvine is known for its weather, its lifestyle, its exceptionally low crime rate, and just about anything else that could be good about a city. Just a 40 mile drive away from the insanity of Los Angeles, this is definitely the place to be.",
     :weather => "This is probably what draws everyone to Irvine in the first place. The weather is absolutely brilliant; most days are nice and sunny, but not in the hot and humid Indian way. The cool breeze the Pacific Ocean brings along is refreshing, and you won’t get baked in the heat even in the afternoon. Temperatures very rarely go beyond 24-25°C, and very rarely go below 14-15°C. All in all, it’s quite lovely.",
     :university_link => 'https://uci.edu/', :university_desc => "The University of California – Irvine is a public research university located, as the name quite clearly gives away, in Irvine, California. Founded in 1965, it’s a relatively new university but has very quickly climbed up the rankings and is definitely among the Tier 1 universities, which should explain its rating as a Public Ivy League. The excellent research program, coupled with the location and doors it opens for you, means that it’s a hot favourite for students from all over the world. Pity it’s not terribly easy to get into, but it’s not extremely hard either."},

    {:rank => 37, :university_name => 'Northeastern University', :university_type => 'Private', :acceptance_rate => 36,
     :tuition => '$25,000', :location => "NEU is located in Downtown Boston, which is definitely one of the busiest and exciting places in the world. Nearby you also have Boston University, which means that you are in the midst of about 2,00,000 students at any given point of time. Quite astonishing, really.",
     :weather => "Boston has snowy weather for a major part of the year. Fall is the best period as the temperature is quite average and bearable. Sometimes, it snows during summer. Weird!",
     :university_link => 'https://www.northeastern.edu/', :university_desc => "Northeastern University is a private research Institution located in Boston, Massachusetts, started in 1898. It’s a popular university amongst Indians. Most of the courses offered by this university are highly rated, and we believe that this has a lot to do with its strategic location."},

    {:rank => 39, :university_name => 'Yale University', :university_type => 'Private', :acceptance_rate => 14,
     :tuition => '$39,000', :location => "Located in New Haven, Connecticut, USA, Yale University is a central part of city’s economy (being its biggest taxpayer and employer). People willing to bring cars must know that parking meters in New Haven are for $1.5 per hour. There is a free 'Yale Shuttle Service' that provides transportation between the University and various areas nearby. One can also use ‘ZipCars’ for car sharing. Students often use bicycles and rollerblades within the campus. The closest airport is Tweed-New Haven Regional Airport (8 km) and then there is Bradley International Airport (83 km). Yale is in a strategic location as it is not too far from New York, Boston, Philadelphia, etc. Some of the recommended restaurants at New Haven are Pepe’s Pizza, Miya’s, Zinc, Caseus and for good music, one can go to Cafe Nine, Lyric Hall, the Space (out in Hamden), BAR (Wednesday night shows and known for its pizza), etc. The only thing that one needs to be careful about is the crime rate in New Haven with frequent muggings but the counter view is that it has the same crime rate as any city its size. Also, the campus and its immediate area are marked as very safe.",
     :weather => "New Haven's climate is tempered by its location on Long Island Sound. Winters are milder, with less snow accumulation, than inland winters. Typically, summers are moderately warm and humid. Precipitation is evenly spread throughout the year, and heavy snow is unusual in the immediate coastal area.",
     :university_link => 'http://www.yale.edu/', :university_desc => "Yale University is a private Ivy League research university in New Haven, Connecticut. It was founded in 1701 as the ""Collegiate School"" by a group of Congregationalist ministers Yale University comprises three major academic components: Yale College (the undergraduate program), the Graduate School of Arts and Sciences, and the professional schools. In addition, Yale encompasses a wide array of centers and programs, libraries, museums, and administrative support offices. Approximately 11,250 students attend Yale."},

    {:rank => 40, :university_name => 'University of Virginia', :university_type => 'Public', :acceptance_rate => 18,
     :tuition => '$25,300', :location => "UVA is located in the relatively smaller town of Charlottesville in Virginia. It is convenient for students who want a big city experience to travel up to Washington DC which is a 2 hours drive. The local area of Charlottesville is as picturesque as it can get. There are hills and mountains all around along with lakes, ponds and also the river James. Students are more than comfortable with the immediate town as well as there is a variety of options to chill. Culturally the town is balanced and a lot of town’s style is influenced by the University ways. In brief, UVA is located well to keep a student happy and accessible!",
     :weather => "Autumn and spring in UVA are amazing. It is pleasant and the surroundings have an aura of positivity during these times. Overall though, weather is highly unpredictable and rains are erratic. The summers will also seem pretty pleasant with a maximum of 28 degree Celsius. Winters can be extremely cold with lowest temperatures of -3 degree Celsius. Overall, weather isn’t that bad at all but surely isn’t the best of the weathers one expects.",
     :university_link => 'http://www.virginia.edu/', :university_desc => "UVA is located in the relatively smaller town of Charlottesville in Virginia. It is convenient for students who want a big city experience to travel up to Washington DC which is a 2 hours drive. The local area of Charlottesville is as picturesque as it can get. There are hills and mountains all around along with lakes, ponds and also the river James. Students are more than comfortable with the immediate town as well as there is a variety of options to chill. Culturally the town is balanced and a lot of town’s style is influenced by the University ways. In brief, UVA is located well to keep a student happy and accessible!"}

]


universities.each do |university|
  University.create!(university)
end
