# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
universities = [
    {:rank => 1, :university_name => 'Massachusetts Institute of Technology', :university_type => 'Private', :acceptance_rate => 18,
     :tuition => '$49,600', :location => 'Located in Cambridge, Massachusetts, MIT is located on the north shore of the Charles River Basin. The campus is within 3 miles of two major interstate highways, and is less than 6 miles from Logan international airport. The Kendall (or MIT) Station is at a 5 minute walk from the campus. MIT is roughly a 20 minute walk from downtown Boston, and a 30–40 minute walk from Harvard University, which is located just up the river from the MIT campus.',
     :weather => 'If there’s any negative about MIT, then this is it. The climate here is of the continental type. Massachusetts receives about 40 inches of rain annually, fairly evenly distributed throughout the year, slightly wetter during the winter.Summers are warm with average high temperatures in July about 26.7 °C and overnight lows about 15.5 °C. Winters are pretty cold though, with temperatures often going sub-zero.',
     :university_link => 'http://www.mit.edu/', :university_desc => "Although it’ll no doubt be fascinating and highly inspiring to read about MIT, it could also give you a serious inferiority complex. Because Massachusetts Institute of Technology is perhaps the best overall college in the world, and it makes sure its students are no less. To get into MIT, you need to be excellent in everything, and even that probably won’t be enough. MIT is absolutely top-notch in everything, from infrastructure to faculty to extracurriculars to placements to alumni. An interesting bit of trivia: the aggregated revenues of companies founded by MIT alumni would rank as the eleventh largest economy in the world. Now, that's MIT. We associate only one word with MIT - WOW."},

    {:rank => 2, :university_name => 'Stanford University', :university_type => 'Private', :acceptance_rate => 17,
     :tuition => '$16,900', :location => 'Located 35 miles south of San Francisco and 20 miles north of San Jose, Stanford University is in the heart of Northern California’s dynamic Silicon Valley.',
     :weather => 'Most students are of the common opinion that the weather at Stanford is pretty good. Apart from the winter months, when it’s slightly cold and wet, the rest of the year is sunny and pleasant. Stanford University area doesn’t receive snowfall and fortunately doesn’t experience extremes of temperature. It’s pretty normal to see people roaming around in shorts and tshirts.',
     :university_link => 'http://www.stanford.edu/', :university_desc => "The very famous Stanford University is a private research university with a high output, located in Stanford, California. Simply, if anyone gets into Stanford, she/he takes it blindly, as the acceptance rate is a mere 4.8% and financial aids are among the most generous ones. To get an idea of exactly how competitive Stanford is, you don’t have to look further than the long list of prominent companies founded by Stanford alumni- Google, Hewlett-Packard, LinkedIn, Yahoo, and Sun Microsystems. And that’s not even one tenth of the list. Also, it ranks #3 according to U.S. News' 'Best Global Universities Ranking' list."},

    {:rank => 3, :university_name => 'University of California – Berkeley', :university_type => 'Public', :acceptance_rate => 14,
     :tuition => '$28,000', :location => 'University of California – Berkeley is located in the Bay Area of California, a very in-demand and rather expensive area. The university is roughly 5 miles from Oakland, and 12 miles from San Francisco. Anyone who knows will tell you that UC Berkeley has a fantastic location, with Tilden Park and Berkeley Marina pretty close by.',
     :weather => 'Berkeley has a Mediterranean climate, though the temperatures in general are rather lower than what you come to expect in, say, Spain. Summers are cool and dry, while winters are cold and wet. Average temperatures in September (the ‘hottest’ month) are a high of 22.1°C and a low of 13.3°C, while average temperatures in January (the coldest month) are a high of 13.6°C and a low of 6.4°C. Berkeley also experiences rainfall once in a while, mainly during winters, and not much. Snowfall is a rare commodity, and normally takes place only on the peaks of hills.',
     :university_link => 'https://www.berkeley.edu/', :university_desc => "UC Berkeley is the flagship institute of the University of California. Statistically, Berkeley (as it’s called) is the most consistently well ranked university in the world. It has the highest number of distinguished graduate programs ranked in the top 10 in their fields by the United States National Research Council. As you can probably gauge, it isn’t easy to get into Berkeley, unless you have an untouchable academic track record. And rightly so – some of the achievements at this institute are fantastic. To give you an idea, UC Berkeley and its researchers are associated with 6 chemical elements of the periodic table. Now that’s something, isn’t it?"},

    {:rank => 4, :university_name => 'California Institute Of Technology', :university_type => 'Private', :acceptance_rate => 9,
     :tuition => '$48,200', :location => 'Like you probably just read, Caltech is located in Pasadena, which fortunately is just about 18km away from downtown Los Angeles. Sounds like the Best of Both Worlds? Definitely.',
     :weather => 'Berkeley has a Mediterranean climate, though the temperatures in general are rather lower than what you come to expect in, say, Spain. Summers are cool and dry, while winters are cold and wet. Average temperatures in September (the ‘hottest’ month) are a high of 22.1°C and a low of 13.3°C, while average temperatures in January (the coldest month) are a high of 13.6°C and a low of 6.4°C. Berkeley also experiences rainfall once in a while, mainly during winters, and not much. Snowfall is a rare commodity, and normally takes place only on the peaks of hills.',
     :university_link => 'http://www.caltech.edu/', :university_desc => "The highly renowned California Institute of Technology is a private research university started in the year 1891. Located in Pasadena, Caltech has gained a reputation as one of the best technological institutes in the world. Understandably, it receives a massive number of applications from all over the world, including thousands from India. However, it isn’t easy to get in. In fact, Caltech is arguably one of the toughest universities to get into; call it bias, prejudice, or racism, Caltech just doesn’t seem to admit enough Indians. Though we think this perhaps has something to do with the extremely high levels of expectation here, and not much else."},

    {:rank => 4, :university_name => 'University of Michigan - Ann Arbor', :university_type => 'Public', :acceptance_rate => 25,
     :tuition => '$15,000', :location => 'University of Michigan is a 45 minute drive from Detroit, the main city of Michigan. Apart from the University, Ann Arbor is pretty boring but fortunately Detroit is quite accessible.',
     :weather => 'The one downside of studying at Ann Arbor could be the climate. It snows almost for 8-9 months of the year, making it terribly cold. During fall, you can expect to see sunrays once in a while which is a ‘feel good factor’ for students. It can get pretty gloomy most of the year.',
     :university_link => 'https://umich.edu/', :university_desc => "University of Michigan, Ann Arbor, is a public research university which was founded in 1817. UMich is very famous for its research work and has one of the largest research expenditures amongst American Universities.  It is one of the high ranking universities in the States, and thus it’s clearly not easy to get in. Many students still apply, though, putting it in the ‘ambitious’ category, and keeping their fingers firmly crossed."},

    {:rank => 6, :university_name => 'University of Texas at Arlington', :university_type => 'Public', :acceptance_rate => 55,
     :tuition => '$25,200', :location => 'As the name suggests, the university is situated in the large city of Arlington and the enormously huge state of Texas which is densely populated. Arlington is approximately 20 miles from the very famous Dallas and is the seventh largest city in Texas. Being a large city and surrounded by many institutions in the nearby vicinity, Arlington is generally preferred by students from all backgrounds.',
     :weather => 'Arlington is one of the cities in the US of A where you experience extremely hot summers. The Fall period i.e. July to early October, the climate is pretty hot and humid. Boys are generally seen in shorts and t-shirts while girls (hold your breath boys) don skirts/shorts and spaghettis. Arlington is not one of the places where the winters are something to look for. It snows rarely and is quite bearable yet Indians find it cold. Spring and autumn bring pleasant weather in the city.',
     :university_link => 'https://www.uta.edu/uta/', :university_desc => "Founded in 1895, University of Texas at Arlington fondly called as UT Arlington or UTA, is a public research university located in the state of Texas. Even though the university is part of the same group, ‘University of Texas’, the institution is ranked pretty low in the US of A. With the likes of the extremely ambitious Texas Austin and TAMU, followed by the hot favourite Texas at Dallas, Arlington looses out on the big league of Institutions. In spite of this, the college is preferred by a lot of Asians, especially Indians, with just an about average profile for Electrical and Telecomm courses majorly."},

    {:rank => 6, :university_name => 'Carnegie Mellon University', :university_type => 'Private', :acceptance_rate => 27,
     :tuition => '$47,600', :location => 'The main CMU campus is just 3 miles away from downtown Pittsburgh. Public transportation is the only means of commute for most of the students, but that isn’t really a problem since the public transport around here is pretty good. This provided you get used to the bus timings, of course. Also, CMU students can roam around most of Pittsburgh for free with the bus passes the university provides.',
     :weather => 'In a word, gloomy. There are very few days when the sky isn’t obscured by clouds. Summers are pretty humid, but never really hot. Winters, on the other hand, can get extremely cold. Pittsburgh experiences an appreciable amount of snowfall, and snowstorms aren’t uncommon.',
     :university_link => 'http://www.cmu.edu/', :university_desc => "Started in the year 1900, Carnegie Mellon University (CMU) is a private research university in Pittsburgh. It is one of the best colleges for just about any course, which is why it’s a ‘dream college’ for almost every Asian student. It’s pretty expensive, though, so that’s something you have to keep in mind."},


    {:rank => 7, :university_name => 'Purdue University West Lafayette', :university_type => 'Public', :acceptance_rate => 23,
     :tuition => '$31,000', :location => 'West Lafayette, by itself, is at best a college town. It tends to get pretty boring in the immediate surroundings of Purdue, but fortunately Indianapolis is just 70 or so miles away, and you can drive to Chicago and Cincinnati in a couple of hours.',
     :weather => 'It’s rather awful, to be honest, so if random change of climate doesn’t exactly suit you, you should probably stay away from Purdue. The weather changes on a weekly basis – there could be a snowstorm one week, and it could become warm and humid the next. Summers are warm and winters are terribly cold, but there isn’t much differentiating which comes when.',
     :university_link => 'http://www.purdue.edu/', :university_desc => "Started in 1869, Purdue University is a public research university located in West Lafayette, Indiana. It is one of the highest-rated universities in the USA, and rightly so. It is involved in very high levels of research, and has some of the best academic programs to offer. Before you read any further, you ought to know that you need an absolutely mind-boggling profile to get into Purdue. An extremely high GPA, some excellent research work, and a couple of international technical papers can give you a chance of making it to Purdue. Note how we say ‘can’ and not ‘will’ – it really is that hard. To get an idea, even IITians with breathtakingly good profiles find it difficult to get in."},


    {:rank => 8, :university_name => 'Georgia Institute of Technology', :university_type => 'Public', :acceptance_rate => 31,
     :tuition => '$28,000', :location => 'Georgia Tech is located in the beautiful city of Atlanta in Georgia. Now, the institute is more or less part of a ‘student village’, which means that there isn’t really too much in the place apart from the colleges.Fortunately, Atlanta itself is a pretty big city and a really cool place to be in, so students don’t really have to step out much. And that’s a good thing, because there aren’t really any ‘major cities’ around.',
     :weather => 'Atlanta (where Georgia Tech is) has a humid subtropical climate, which means it has extremes of temperatures across the year. Summers are hot and humid, while winters are very cold. The coldest month is normally January, where the average temperature is about 6°C, although temperatures often fall to about -7°C at night. July is normally the warmest month, and temperatures can go as high as 36°C, with 31°C being the average. Atlanta does not receive a terribly high amount of snowfall in spite of the low temperatures, but rainfall occurs almost throughout the year, though it’s never exactly ‘torrential’.',
     :university_link => 'http://www.gatech.edu/', :university_desc => "Georgia Institute of Technology, more commonly known as Georgia Tech, is one of the most reputed public research universities in the world. Founded in 1885, GeorgiaTech initially started with core programs like mechanical, civil and aerospace engineering. But in the early 1900s, it started a host of other programs, and now is highly reputed for ALL of its courses as well. Another thing to be known about Georgia Tech is the fact that it has ‘satellite campuses’ in France, Ireland, China (Shanghai) as well as Singapore. Students are often given options of specialized programs wherein they spend one year at the main GT campus and another year at one of the foreign campuses."},

    {:rank => 9, :university_name => 'North Carolina State University, Raleigh', :university_type => 'Public', :acceptance_rate => 17,
     :tuition => '$26,400', :location => 'NCSU is located in Raleigh, which is the capital city of North Carolina. Raleigh is one of the fastest-growing cities in the country and the city of Raleigh is named after Sir Walter Raleigh, who established the lost Roanoke Colony in present-day Dare County.',
     :weather => "NCSU main campus has three sub campuses, North, Central and South. Although your life would be pretty much centered around the Engineering buildings (which is in the wonderful centennial campus), you should definitely take a few long walks around the rest of the campus, because well, it’s quite breathtakingly beautiful. Added to the fact that all the libraries, laboratories and research centers are state-of-the-art, and you get the perfect ‘university feel’. The gym, recreation center and the sports/athletic facilities are great as well. The brand new Hunt Library is certainly one of the most amazing structures you'll ever see, magnificent and hi-tech, it is the world’s first artificial intelligence involved library.",
     :university_link => 'https://www.ncsu.edu/', :university_desc => "North Carolina State University (NCSU) is a public research university started in 1887. It has an enrollment of over 30,000 students, making it the largest university in Carolina by a margin. NCSU is especially well known for programs like ECE, CSE and Computer Networking (which is offered in very few other universities), and this fact coupled with its low tuition fees makes it a dream college for many students. It ranks #217 according to U.S. News' 'Best Global Universities Ranking' list."},

    {:rank => 9, :university_name => 'University of Illinois at Urbana-Champaign', :university_type => 'Public', :acceptance_rate => 26,
     :tuition => '$34,400', :location => 'As you probably figured out, UIUC is located in the twin cities of Urbana and Champaign, in the state of Illinois. While there isn’t too much to say about the immediate location, UIUC is fortuitously just about 3 hours or so away from Chicago, which is a common weekend ‘retreat’ back to civilization for students.',
     :weather => "Urbana-Champaign is infamous for its frankly awful and unpredictable weather. Winters are biting cold and summers can get pretty hot. Most students carry an umbrella or a raincoat around at most times, since it can rain any time of the year. The twin cities receive ample amount of snowfall in winters, and students walking into class semi-frozen isn’t an uncommon sight.",
     :university_link => 'http://www.illinois.edu/', :university_desc => "University of Illinois – Urbana Champaign is a public research university, started in 1859. Because of its glorious history and excellent opportunity, it is widely regarded as the best public university in the States. That was the good news. The bad news is that it’s awfully hard to get into UIUC, and next to impossible for Indians, unless they have fantastic profiles. No no no, it’s not racism. It’s just that, well, people tend to have better profiles than the average Indian."},

    {:rank => 10, :university_name => 'University of Southern California', :university_type => 'Private', :acceptance_rate => 23,
     :tuition => '$32,100', :location => 'The University Park Campus of USC is in the West Adam’s district of South Los Angeles. The campus is within walking distance from LA Coliseum and Staple Centre, House of the LA Lakers.',
     :weather => "Weather at the Southern California is pretty decent as there is enough sunlight during the day time which makes it sufficiently hot while the nights are cool enough to bear the weather. Fall period is quite hot while rain showers are the standard customers during winter.",
     :university_link => 'http://www.illinois.edu/', :university_desc => "The University of Southern California is a private research University which was founded in 1880, making it California’s oldest private university. USC is involved in very high level research activity and thus has quickly risen up the ranking.  It may interest you that although USC claims that their students hail from 112 countries, but it feels a lot like India once you’re there."}

]


universities.each do |university|
  University.create!(university)
end
